import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, ArrowUpRight, Check, ChevronRight, Command, Layers3, LockKeyhole, Menu, MessageCircle, ShieldCheck, Sparkles, X } from 'lucide-react'
import { motion } from 'framer-motion'
import Brand from '../components/Brand'
import ModelIcon from '../components/ModelIcon'
import ThemeToggle from '../components/ThemeToggle'
import { api, type Model } from '../lib/api'
import { useAuth } from '../contexts/AuthContext'

export default function Landing({ theme, toggleTheme }: { theme: 'light' | 'dark'; toggleTheme: () => void }) {
  const { user } = useAuth()
  const [models, setModels] = useState<Model[]>([])
  const [mobileOpen, setMobileOpen] = useState(false)
  useEffect(() => { api<Model[]>('models').then(setModels).catch(() => {}) }, [])
  const destination = user ? '/app' : '/signup'
  return <div className="landing">
    <div className="announcement"><span className="announcement-spark">✳</span> Your best ideas deserve every perspective. <Link to={destination}>Explore FLAX <ArrowRight size={13}/></Link></div>
    <header className="site-header container"><Brand/><nav className={mobileOpen ? 'site-nav open' : 'site-nav'}><a href="#why" onClick={() => setMobileOpen(false)}>Why FLAX</a><a href="#models" onClick={() => setMobileOpen(false)}>Models</a><a href="#how" onClick={() => setMobileOpen(false)}>How it works</a></nav><div className="header-actions"><ThemeToggle theme={theme} toggle={toggleTheme}/><Link className="header-login" to={user ? '/app' : '/login'}>{user ? 'Dashboard' : 'Log in'}</Link><Link className="btn btn-dark header-cta" to={destination}>Get started <ArrowUpRight size={16}/></Link><button className="icon-button mobile-menu" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Toggle menu">{mobileOpen ? <X size={20}/> : <Menu size={20}/>}</button></div></header>
    <main>
      <section className="hero container"><div className="hero-copy"><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .5 }} className="eyebrow"><span className="eyebrow-line"/> THE INTELLIGENT WAY FORWARD</motion.div><motion.h1 initial={{ opacity: 0, y: 22 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .08, duration: .65 }}>One place for<br/><span>every AI<span className="hero-period">.</span></span></motion.h1><motion.p initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .17, duration: .6 }}>The world's most capable minds, all in one thoughtful workspace. Choose your model, follow your curiosity, and make more of every idea.</motion.p><motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .26, duration: .5 }} className="hero-actions"><Link to={destination} className="btn btn-dark btn-large">Start creating <ArrowUpRight size={19}/></Link><a href="#how" className="text-link">See how it works <ChevronRight size={17}/></a></motion.div><div className="hero-footnote"><span className="tiny-avatars"><span>✳</span><span>✦</span><span>●</span></span><span>One workspace. Endless possibilities.</span></div></div>
      <motion.div initial={{ opacity: 0, scale: .94, x: 20 }} animate={{ opacity: 1, scale: 1, x: 0 }} transition={{ delay: .16, duration: .7 }} className="hero-art" aria-label="Illustration of connected AI models"><div className="art-grain"/><div className="art-grid"/><div className="art-orbit orbit-1"/><div className="art-orbit orbit-2"/><div className="art-orbit orbit-3"/><div className="orbit-node node-one"><Sparkles size={23}/></div><div className="orbit-node node-two"><Command size={22}/></div><div className="orbit-node node-three"><Layers3 size={21}/></div><div className="center-glow"/><div className="art-core"><span className="core-icon">✳</span><span>FLAX</span></div><div className="float-card float-card-top"><span className="float-pulse"/> Your ideas, amplified</div><div className="float-card float-card-bottom"><span className="mini-bars"><i/><i/><i/></span> All your AI, in sync</div><div className="art-caption">A WHOLE UNIVERSE OF THINKING, ONE PLACE.</div></motion.div></section>
      <section className="trust-strip"><div className="container trust-inner"><span>ONE WORKSPACE, MORE POSSIBILITY</span><div><span><Check size={15}/> Multiple models</span><span><Check size={15}/> One conversation space</span><span><Check size={15}/> Built around you</span></div></div></section>
      <section id="why" className="section container why-section"><div className="section-heading"><div><span className="section-kicker">/ 01 &nbsp; A BETTER WAY TO THINK</span><h2>More than a chat.<br/><em>A new point of view.</em></h2></div><p>Great work rarely comes from a single perspective. FLAX brings the right intelligence into your flow, exactly when you need it.</p></div><div className="feature-grid"><article className="feature-card feature-accent"><div className="feature-icon"><Layers3 size={24}/></div><div className="feature-graphic graphic-layers"><span/><span/><span/></div><h3>Many minds. One space.</h3><p>Go from brainstorming to building without switching tabs or losing your train of thought.</p><span className="feature-number">01 / CONNECT</span></article><article className="feature-card"><div className="feature-icon"><MessageCircle size={24}/></div><div className="feature-graphic graphic-chat"><span className="bubble-a"/><span className="bubble-b"/><span className="bubble-c"/></div><h3>Conversations that stay.</h3><p>Every thread has a home. Pick up where you left off, whenever inspiration strikes.</p><span className="feature-number">02 / CONTINUE</span></article><article className="feature-card"><div className="feature-icon"><ShieldCheck size={24}/></div><div className="feature-graphic graphic-shield"><ShieldCheck size={84} strokeWidth={1}/></div><h3>Thoughtfully private.</h3><p>Your workspace is yours. Secure sessions and server-side AI access keep the important things protected.</p><span className="feature-number">03 / CREATE</span></article></div></section>
      <section id="models" className="models-section"><div className="container models-inner"><div className="models-copy"><span className="section-kicker">/ 02 &nbsp; THE RIGHT MIND FOR THE MOMENT</span><h2>One question.<br/><em>More possibilities.</em></h2><p>Different problems call for different strengths. Find your flow with a curated selection of leading AI models in one seamless space.</p><Link to={destination} className="text-link">Meet your new workspace <ArrowUpRight size={17}/></Link></div><div className="model-stack">{models.length ? models.slice(0, 3).map((model, index) => <div className="model-stack-card" key={model.id} style={{ transform: `translateX(${index * 12}px)` }}><ModelIcon provider={model.provider} size={22}/><div><strong>{model.display_name}</strong><span>{model.description}</span></div><ArrowUpRight size={17}/></div>) : <div className="model-stack-loading"><div/><div/><div/></div>}<div className="stack-note"><Sparkles size={16}/> Switch perspectives, not platforms.</div></div></div></section>
      <section id="how" className="section container how-section"><span className="section-kicker">/ 03 &nbsp; BEAUTIFULLY SIMPLE</span><h2>Less setup.<br/><em>More spark.</em></h2><div className="steps"><div><span className="step-num">01</span><h3>Make yourself at home</h3><p>Create your space in a moment. Your conversations will be ready whenever you return.</p></div><div><span className="step-num">02</span><h3>Pick your perspective</h3><p>Choose the model that fits the moment, from creative thinking to deep reasoning.</p></div><div><span className="step-num">03</span><h3>Follow the thought</h3><p>Ask, explore, build, and keep every good idea moving forward.</p></div></div></section>
      <section className="cta-section container"><div className="cta-orb"/><div className="cta-text"><span className="section-kicker">YOUR NEXT IDEA STARTS HERE</span><h2>See what happens<br/>when minds meet<span>.</span></h2><p>A more connected way to think is waiting for you.</p><Link to={destination} className="btn btn-lime btn-large">Get started with FLAX <ArrowUpRight size={19}/></Link></div><span className="cta-symbol">✳</span></section>
    </main><footer className="site-footer container"><div><Brand/><p>One place for every AI.</p></div><div className="footer-links"><a href="#why">Why FLAX</a><a href="#models">Models</a><a href="#how">How it works</a><Link to={user ? '/app' : '/login'}>Workspace</Link></div><span>© {new Date().getFullYear()} FLAX AI. Made for curious minds.</span></footer>
  </div>
}
